### ISSUE TITLE
Revoked certificates are not archived

### ISSUE THREAD

**Issue by jsmad** [lukas2511/dehydrated#383] opened 2017-04-23 16:08 UTC
The --cleanup command does not move files like "cert-123-pem-revoked" to the archive directory.

Is this by design, or should the cleanup procedure actually move those files as well?

Thank you.

**Comment by txr13** [comment] 2017-04-23 16:40
This is (as far as I can tell) by design. The cleanup procedure checks the symlinks to determine the current targets, then archives the files of that type that are not currently linked.

I'm going just from memory here, but I believe this procedure doesn't work for revoked files, since they're no longer in the same naming convention as the subroutine checks for.

This is a duplicate of #237. I've been meaning to write some code to address this, but I haven't figured out a good way to archive all revoked certs without touching any other user-created files in the filespace...

**Comment by jsmad** [comment] 2017-04-25 08:00
It's not a bug, it is a *feature* :)

Just kidding, I am glad someone is aware of the problem and I am sure it will get sorted out eventually.

**Comment by lukas2511** [comment] 2017-07-10 18:41
Fixed in dc600e39b8643767bcaa265c0e0ad3039c757073.

**Closed by lukas2511** 2017-07-10 18:41 UTC
