### ISSUE TITLE
Let people try the staging CA before pointing to the production CA

### ISSUE THREAD

**Issue by giminni** [lukas2511/dehydrated#274] opened 2016-09-14 15:23 UTC
Hi Lukas,
nice script. BTW I tested it with the staging CA before going to real life.

#Path to certificate authority (default: https://acme-v01.api.letsencrypt.org/directory)
#CA="https://acme-v01.api.letsencrypt.org/directory"
CA_PROD="https://acme-v01.api.letsencrypt.org/directory"
CA_TEST="https://acme-staging.api.letsencrypt.org/directory"
CA="${CA_TEST}"

**Comment by welwood08** [comment] 2016-09-15 16:03
Duplicate of #72?

**Comment by lukas2511** [comment] 2016-09-17 11:28
People can try the staging CA if they want to, it's documented in [docs/staging.md](https://github.com/lukas2511/dehydrated/blob/master/docs/staging.md).

I don't want to always have to configure the production CA when using this and it may (again) break a lot of setups, so this won't be changed.

**Closed by lukas2511** 2016-09-17 11:28 UTC
