### ISSUE TITLE
support generating keys for more than one key algorithm

### ISSUE THREAD

**Issue by martin21** [lukas2511/dehydrated#527] opened 2018-04-02 19:15 UTC
Currently it seems KEY_ALGO can only be set to one value. I´d like dehydrated to generate RSA *and* secp384r1 keys automatically.

I think I may work with two config files, two cron jobs and two different certificate directories but for example acme.sh can do both. So it would be nice if dehydrated can do it as well.

**Comment by lukas2511** [comment] 2018-04-02 19:16
Duplicate of #499. Thanks for the suggestion anyway! I'll be working on this very soon!

**Closed by lukas2511** 2018-04-02 19:16 UTC

**Comment by martin21** [comment] 2018-04-02 19:28
Sorry, I missed #499 as I looked for duplicates. Subscribed there. Thank you.
