### ISSUE TITLE
Please ignore hook/* instead of just hook.sh

### ISSUE THREAD

**Issue by bviktor** [lukas2511/dehydrated#441] opened 2017-10-06 15:27 UTC
A lot of hooks have several files instead of just `hook.sh` so it'd be really helpful. Whatcha think?

**Comment by lukas2511** [comment] 2017-12-13 23:25
Duplicate of #270.

I don't think this is a good idea. With per-certificate hooks and everything this would just become a mess and I don't really see it helpful in any way. If you really need it use a wrapper-script.

**Closed by lukas2511** 2017-12-13 23:25 UTC
