### ISSUE TITLE
Feature request - allow update of email address

### ISSUE THREAD

**Issue by nneul** [lukas2511/dehydrated#328] opened 2016-12-30 21:05 UTC
According to 

https://github.com/certbot/certbot/issues/1215

---------
The API to do this already exists on the boulder side, POSTing a registration object with a changed contacts field to /acme/reg should update the registration.
----------

It would be nice if there were an option to do this in dehydrated client. Or even better - do it automatically if the address in the config doesn't match the address in registration_info.json

**Comment by txr13** [comment] 2016-12-30 21:28
It would be very helpful to have a way to update contact info from dehydrated.

I'm not as sure about updating it automatically when a change is made to the config, though... Given that the client can support multiple config files and multiple ACME servers, I think I would personally prefer that the contact update operation only be issued through manual invocation, rather than having something put through automatically.

**Comment by nneul** [comment] 2016-12-30 21:30
Perhaps a "Your contact information in configuration doesn't match registration, exiting..." error (or warning), combined with a "--update-registration" option that would cause it to react to that situation by updating the registration if needed.

**Comment by txr13** [comment] 2016-12-30 21:42
I like the thought of a notification being dropped into the logs, possibly notated as a warning. Shouldn't cause the client to exit or abort the current execution.

--update-registration (or whatever the option is) should be able to be executed on its own. That is, without an accompanying -c or -d options.

In my own environment (for example), dehydrated is running under cron. I don't want changed contact info to abort a scheduled run... but if a notification / warning popped up in my cron logs, I'd be happy to log in and manually do an --update-registration to address that.

**Comment by lukas2511** [comment] 2017-01-09 10:58
Duplicate of #239, closing this.

**Closed by lukas2511** 2017-01-09 10:58 UTC
